'use client';
import {useEffect,useRef,useState} from 'react';
import {Sprout,Sun,Moon,Swords,CookingPot,Volume2,VolumeX,HelpCircle,ArrowRight,Leaf,Droplets,FlaskConical,Mountain,Heart,Wind,Flame,Check,Lock,ChevronRight,Pause,Play,Home as HomeIcon,Star,Package,ArrowUp,ArrowDown,ArrowLeft} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {CROPS,HEROES,freshFarm,type CropId,type HeroId} from '@/lib/game/state';
import type {WildseedGame,View} from '@/lib/game/scene';

const cropIds=Object.keys(CROPS) as CropId[];
const initial:View={farm:freshFarm(),mode:'farm',ready:false,error:'',selected:0,seed:'sunroot',hp:100,maxHp:100,time:0,kills:0,level:1,dash:0,loot:{sunroot:0,moonberry:0,embercorn:0,fertilizer:0,soil:0},upgrade:false,result:null,message:'',paused:false,saved:true,meal:null,tier:1};
function CropIcon({id,size=21}:{id:CropId;size?:number}){return id==='sunroot'?<Sprout size={size}/>:id==='moonberry'?<Moon size={size}/>:<Flame size={size}/>;}
function countTime(t:number){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');}

export default function Home(){
 const mount=useRef<HTMLDivElement>(null),game=useRef<WildseedGame|null>(null);
 const [v,setV]=useState<View>(initial),[started,setStarted]=useState(false),[modal,setModal]=useState<'kitchen'|'travel'|'help'|'hero'|'garden'|'inventory'|null>(null),[muted,setMuted]=useState(true),[userPaused,setUserPaused]=useState(false);
 useEffect(()=>{let cancelled=false;import('../lib/game/scene').then(({WildseedGame})=>{if(cancelled||!mount.current)return;try{game.current=new WildseedGame(mount.current,setV);}catch(e){console.error(e);setV(s=>({...s,error:'This browser could not start 3D graphics. Try a browser with WebGL enabled.'}));}}).catch(()=>setV(s=>({...s,error:'The game could not load. Please reload to try again.'})));return()=>{cancelled=true;game.current?.dispose();game.current=null;};},[]);
 useEffect(()=>{game.current?.setPaused(Boolean(modal)||userPaused);},[modal,userPaused]);
 const p=v.farm.plots[v.selected],hero=HEROES[v.farm.hero],isFarm=v.mode==='farm';
 const actLabel=!p.crop?'Plant':p.growth>=1?'Harvest':!p.watered?'Water':Math.round(p.growth*100)+'%';
 const open=(name:typeof modal)=>{setModal(name);};
 const launch=(tier:number)=>{setModal(null);setUserPaused(false);game.current?.expedition(tier);};
 const setMute=()=>{setMuted(!muted);game.current?.setMuted(!muted);};
 return <main className={'game-shell '+(!isFarm?'in-dungeon':'')}>
  <div className="world" ref={mount} aria-label="Interactive 3D Axie farm and survival arena"/>

  <header className="topbar quiet-topbar">
   <div className="wordmark"><Sprout/><strong>Wildseed</strong></div>
   <div className="day-chip" aria-label={isFarm?'Day '+v.farm.day:'Expedition time'}>{isFarm?<Sun size={18}/>:<Moon size={18}/>} {isFarm?v.farm.day:countTime(v.time)+' / 1:30'}</div>
   <nav className="utility" aria-label="Game controls">
    {started&&isFarm&&<><button title="Garden beds" aria-label="Garden beds" onClick={()=>open('garden')}><Sprout size={20}/></button><button title="Kitchen" aria-label="Kitchen" onClick={()=>open('kitchen')}><CookingPot size={20}/></button><button title="Explore dungeons" aria-label="Explore dungeons" onClick={()=>open('travel')}><Swords size={20}/></button></>}
    {started&&!isFarm&&<button title="Expedition pouch" aria-label="Expedition pouch" onClick={()=>open('inventory')}><Package size={20}/></button>}
    <button title={muted?'Enable sound':'Mute sound'} aria-label={muted?'Enable sound':'Mute sound'} onClick={setMute}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button>
    {started&&<button title={userPaused?'Resume':'Pause'} aria-label={userPaused?'Resume':'Pause'} onClick={()=>setUserPaused(!userPaused)}>{userPaused?<Play size={18}/>:<Pause size={18}/>}</button>}
    <button title="Help & credits" aria-label="Help & credits" onClick={()=>open('help')}><HelpCircle size={20}/></button>
   </nav>
  </header>
  {!started&&<section className="quiet-welcome panel"><h1>Welcome home.</h1><button className="primary" disabled={!v.ready||!!v.error} onClick={()=>{setStarted(true);game.current?.start();}}>{v.ready?'Play':'Loading...'}<Play size={18}/></button></section>}
  {started&&isFarm&&<>
   <button className="companion-button panel" title={'Change Axie · '+hero.name} aria-label={'Change Axie · '+hero.name} onClick={()=>open('hero')}><img src={'/assets/axie/'+v.farm.hero+'.png'} alt=""/></button>
   <div className="farm-dock panel" aria-label="Garden actions">
    <div className="seed-slots" aria-label="Select a seed">{cropIds.map((id,i)=><button key={id} className={'seed-slot '+id+(v.seed===id?' active':'')} title={CROPS[id].name+' · '+v.farm.seeds[id]+' seeds · '+(i+1)} aria-label={CROPS[id].name+' · '+v.farm.seeds[id]+' seeds'} aria-pressed={v.seed===id} onClick={()=>game.current?.selectSeed(id)}><CropIcon id={id}/><b>{v.farm.seeds[id]}</b></button>)}</div>
    <div className="tend-slot"><button className="bed-selector" title="Choose a garden bed" onClick={()=>open('garden')}>Bed {v.selected+1}<ChevronRight size={13}/></button><button className="primary compact-tend" disabled={!!p.crop&&p.watered&&p.growth<1||!p.crop&&v.farm.seeds[v.seed]<1} onClick={()=>game.current?.tendPlot()}>{p.crop&&!p.watered&&p.growth<1?<Droplets size={17}/>:<Sprout size={17}/>} {actLabel}<kbd>E</kbd></button></div>
    <div className="supply-slots"><button title="Fertilizer · Speed up this crop" aria-label={'Fertilize selected bed · '+v.farm.fertilizer+' available'} disabled={!p.crop||p.growth>=1||p.fertilized||v.farm.fertilizer<1} onClick={()=>game.current?.improvePlot('fertilizer')}><FlaskConical size={20}/><b>{v.farm.fertilizer}</b></button><button title="Rich soil · Improve growth and yield" aria-label={'Improve selected bed soil · '+v.farm.soil+' available'} disabled={p.rich||v.farm.soil<1} onClick={()=>game.current?.improvePlot('soil')}><Mountain size={20}/><b>{v.farm.soil}</b></button></div>
   </div>
  </>}
  {started&&!isFarm&&<>
   <aside className="vitals panel" aria-label="Expedition status"><img src={'/assets/axie/'+v.farm.hero+'.png'} alt={hero.name}/><div className="vitals-bars"><div><Heart size={14}/><b>{Math.ceil(v.hp)} / {v.maxHp}</b><span title="Level"><Star size={14}/>{v.level}</span></div><Progress value={v.hp/v.maxHp*100} className="health-progress" aria-label="Health"/></div></aside>
   <button className="compact-dash panel" title="Dash · Space" aria-label="Dash" disabled={v.dash>0} onClick={()=>game.current?.dashNow()}><Wind size={23}/>{v.dash>0?v.dash.toFixed(1)+'s':<kbd>SPACE</kbd>}</button>
  </>}

  {started&&<div className="touch-controls" aria-label="Touch movement">{[['w',ArrowUp],['a',ArrowLeft],['s',ArrowDown],['d',ArrowRight]].map(([key,Icon])=>{const I=Icon as typeof ArrowUp;return <button key={key as string} aria-label={'Move '+key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);game.current?.moveKey(key as string,true);}} onPointerUp={()=>game.current?.moveKey(key as string,false)} onPointerCancel={()=>game.current?.moveKey(key as string,false)}><I size={23}/></button>;})}</div>}
  {v.message&&started&&!modal&&!v.result&&!v.upgrade&&<output className="toast" aria-live="polite"><Leaf size={18}/>{v.message}</output>}
  {userPaused&&!modal&&<div className="pause-cover"><div className="panel pause-card"><Moon size={30}/><h2>Paused</h2><button className="primary" onClick={()=>setUserPaused(false)}><Play size={18}/> Resume</button></div></div>}
  {v.error&&<div className="error-panel panel" role="alert"><h2>Lunacia needs a moment</h2><p>{v.error}</p><button className="primary" onClick={()=>location.reload()}>Reload game</button></div>}
  <Dialog open={modal!==null} onOpenChange={value=>{if(!value)setModal(null);}}><DialogContent className="game-dialog">
   <DialogTitle className="dialog-title">{modal==='kitchen'?'Kitchen':modal==='travel'?'Explore':modal==='hero'?'Your Axie':modal==='garden'?'Garden':modal==='inventory'?'Expedition pouch':'How to play'}</DialogTitle>
   <DialogDescription>{modal==='kitchen'?'Turn two crops into a meal. Pack one boost for your next expedition.':modal==='travel'?'Seeds, fertilizer, and rich soil are waiting beyond the garden.':modal==='hero'?'Choose your companion.':modal==='garden'?'Choose a bed, then plant, water, or harvest with E.':modal==='inventory'?'Survive 90 seconds and defeat the guardian to keep every find.':'Grow, cook, explore. Bring your next harvest home.'}</DialogDescription>

   {modal==='garden'&&<div className="garden-menu"><div className="plot-grid" aria-label="Garden beds">{v.farm.plots.map((plot,i)=><button key={i} className={(v.selected===i?'selected ':'')+(plot.crop&&plot.growth>=1?'ripe ':'')+(plot.rich?'rich ':'')} title={'Bed '+(i+1)+(plot.crop?' · '+CROPS[plot.crop].name:' · Empty')} aria-label={'Select bed '+(i+1)} aria-pressed={v.selected===i} onClick={()=>game.current?.selectPlot(i)}>{plot.crop?<CropIcon id={plot.crop}/>:<span>+</span>}{plot.crop&&!plot.watered&&<i className="water-dot"/>}{plot.crop&&plot.growth>=1&&<i className="ripe-dot"/>}</button>)}</div><div className="bed-state"><strong>Bed {v.selected+1}</strong><span>{p.crop?CROPS[p.crop].name+' · '+(p.growth>=1?'Ready':p.watered?Math.round(p.growth*100)+'%':'Needs water'):'Empty'}{p.rich?' · Rich soil':''}</span></div><button className="primary" onClick={()=>setModal(null)}>Tend this bed <Sprout size={18}/></button></div>}
   {modal==='inventory'&&<div>{cropIds.map(id=><div className="loot-row" key={id}><CropIcon id={id} size={18}/><span>{CROPS[id].name} seeds</span><b>{v.loot[id]}</b></div>)}<div className="loot-row"><FlaskConical size={18}/><span>Fertilizer</span><b>{v.loot.fertilizer}</b></div><div className="loot-row"><Mountain size={18}/><span>Rich soil</span><b>{v.loot.soil}</b></div><div className="loot-row"><Swords size={18}/><span>Defeated</span><b>{v.kills}</b></div>{v.meal&&<p>{CROPS[v.meal].meal}: {CROPS[v.meal].effect}</p>}<button className="secondary return-button" onClick={()=>{setModal(null);game.current?.escape();}}><HomeIcon size={16}/> Return early</button><small className="fine-print">An early return keeps half your finds.</small></div>}

   {modal==='kitchen'&&<div className="recipes">{cropIds.map(id=><article className="recipe" key={id}><span className={'recipe-icon '+id}><CropIcon id={id} size={29}/></span><div><h3>{CROPS[id].meal}</h3><p>{CROPS[id].effect}</p><small>2 {CROPS[id].name} · You have {v.farm.crops[id]}</small></div><div className="recipe-actions"><button className="secondary" disabled={v.farm.crops[id]<2} onClick={()=>game.current?.cookMeal(id)}>Cook</button><button className={'secondary '+(v.farm.meal===id?'equipped':'')} disabled={v.farm.meals[id]<1} onClick={()=>game.current?.equipMeal(id)}>{v.farm.meal===id?<Check size={15}/>:<Package size={15}/>} {v.farm.meal===id?'Packed':'Pack'} ({v.farm.meals[id]})</button></div></article>)}<p className="dialog-note">One packed meal is consumed when you enter a dungeon. Your garden keeps growing during expeditions.</p></div>}
   {modal==='travel'&&<div className="destinations"><article className="destination grove"><span className="destination-number">01</span><div><span className="eyebrow">THE FIRST STEPS</span><h3>Whispering Grove</h3><p>A gentle forest with restless roots. Bring home Sunroot, Moonberry, and garden supplies.</p><span className="difficulty"><Leaf size={15}/> First expedition · 90 seconds + guardian</span><button className="primary" onClick={()=>launch(1)}>Enter the grove <ArrowRight size={18}/></button></div></article><article className={'destination bramble '+(!v.farm.unlocked?'locked':'')}><span className="destination-number">{v.farm.unlocked?'02':<Lock size={26}/>}</span><div><span className="eyebrow">A RARER HARVEST</span><h3>Bramble Hollow</h3><p>Stronger creatures guard the rare Embercorn seeds. A good meal goes a long way.</p>{v.farm.unlocked?<button className="primary" onClick={()=>launch(2)}>Enter the hollow <ArrowRight size={18}/></button>:<div className="gate-offering"><span className="unlock-hint">Offer 4 Sunroot + 2 Moonberry</span><div className="offering-counts"><span><Sprout size={16}/>{v.farm.crops.sunroot} / 4</span><span><Moon size={16}/>{v.farm.crops.moonberry} / 2</span></div><button className="secondary" disabled={v.farm.crops.sunroot<4||v.farm.crops.moonberry<2} onClick={()=>game.current?.unlock()}>Unlock <Lock size={15}/></button></div>}</div></article><div className="packed-note"><CookingPot size={18}/>{v.farm.meal?'Packed: '+CROPS[v.farm.meal].meal+' · '+CROPS[v.farm.meal].effect:'No meal packed. You can still explore.'}</div></div>}
   {modal==='hero'&&<div className="hero-options">{(Object.keys(HEROES) as HeroId[]).map(id=><button className={'hero-option '+(v.farm.hero===id?'chosen':'')} key={id} onClick={()=>game.current?.selectHero(id)}><img src={'/assets/axie/'+id+'.png'} alt={HEROES[id].name}/><h3>{HEROES[id].name}</h3><span>{HEROES[id].role}</span><p>{HEROES[id].perk}</p><span className="choose-label">{v.farm.hero===id?'Your companion':'Choose Axie'}{v.farm.hero===id?<Check size={16}/>:<ArrowRight size={16}/>}</span></button>)}</div>}
   {modal==='help'&&<div className="help-content"><ol><li><strong>Grow.</strong> Click a garden bed or use the leaf menu, choose a seed (1–3), then press E to plant, water, or harvest. Crops grow while you play.</li><li><strong>Look around.</strong> Drag the world to rotate the camera; scroll or pinch to zoom. V resets the view behind your Axie. WASD moves relative to the camera.</li><li><strong>Prepare.</strong> Cook two crops at the camp kitchen. Pack one meal for health, speed, or damage.</li><li><strong>Explore.</strong> Attacks fire automatically. Move with WASD, arrow keys, or click/tap the ground. Space dashes.</li><li><strong>Bring it home.</strong> Defeated creatures yield supplies. Win for the full haul, or keep half if you return early or fall.</li><li><strong>Go deeper.</strong> Open the swords menu and offer 4 Sunroot and 2 Moonberry to unlock Bramble Hollow and rare Embercorn.</li></ol><p>Garden progress saves locally in this browser. Farming pauses when this tab is hidden or a menu is open.</p><div className="credits"><strong>Made for Axie Vibeathon</strong><p>Axie and Sapidae characters, models, textures and animations belong to Sky Mavis and its licensors. Supplied via the event's Axie 3D asset pack. Environment, crop designs and game systems are original prototype work.</p><a href="/licenses/axie-3d-RIGHTS.md" target="_blank" rel="noreferrer">Axie asset permission ↗</a><a href="/licenses/axie-3d-THIRD_PARTY_NOTICES.md" target="_blank" rel="noreferrer">Third-party notices ↗</a><small>Unofficial work in progress. No wallet needed.</small></div></div>}
  </DialogContent></Dialog>
  <Dialog open={v.upgrade} onOpenChange={()=>{}}><DialogContent className="game-dialog upgrade-dialog" showCloseButton={false}><DialogTitle className="dialog-title">A little stronger.</DialogTitle><DialogDescription>Choose a gift for this expedition. The wilds can wait.</DialogDescription><div className="upgrade-options">{[{id:'damage',Icon:Flame,title:'Wild roots',text:'+30% attack damage'},{id:'speed',Icon:Wind,title:'Light paws',text:'+15% movement speed'},{id:'health',Icon:Heart,title:'Second wind',text:'+20 max health & heal 50'}].map(u=><button key={u.id} onClick={()=>game.current?.chooseUpgrade(u.id as 'damage'|'speed'|'health')}><u.Icon size={32}/><h3>{u.title}</h3><p>{u.text}</p><span>Choose <ArrowRight size={16}/></span></button>)}</div></DialogContent></Dialog>
  <Dialog open={v.result!==null} onOpenChange={value=>{if(!value)game.current?.dismissResult();}}><DialogContent className="game-dialog result-dialog"><DialogTitle className="dialog-title">{v.result?.outcome==='won'?'A pocketful of possibilities.':v.result?.outcome==='lost'?'Home is always here.':'A safe journey home.'}</DialogTitle><DialogDescription>{v.result?.outcome==='won'?'Guardian defeated. Your next harvest starts here.':'You kept half your finds and a small seed pouch. Plant, prepare, and try again.'}</DialogDescription>{v.result&&<><div className="result-stats"><span><Swords size={18}/>{v.result.kills} creatures defeated</span><span><Sun size={18}/>Day {v.farm.day}</span></div><div className="result-loot">{cropIds.map(id=><div key={id}><CropIcon id={id} size={24}/><strong>+{v.result!.loot[id]}</strong><span>{CROPS[id].name} seeds</span></div>)}<div><FlaskConical size={24}/><strong>+{v.result.loot.fertilizer}</strong><span>Fertilizer</span></div><div><Mountain size={24}/><strong>+{v.result.loot.soil}</strong><span>Rich soil</span></div></div><button className="primary" onClick={()=>game.current?.dismissResult()}>Back to my garden <Sprout size={18}/></button></>}</DialogContent></Dialog>
 </main>;
}

