import assert from 'node:assert/strict';
import {freshFarm,tend,grow,improve,cook,offerHarvest,beginExpedition,settleExpedition,emptyLoot,rewardKill,hydrateFarm} from '../lib/game/state.ts';
let passed=0;function check(name,fn){fn();console.log('PASS '+name);passed++;}
check('First harvest connects to meals and gate unlock',()=>{const f=freshFarm();for(let i=0;i<4;i++)tend(f,i,'sunroot',()=>1);assert.equal(f.crops.sunroot,6);assert.equal(f.crops.moonberry,2);cook(f,'sunroot');assert.equal(f.meals.sunroot,1);assert.equal(f.crops.sunroot,4);offerHarvest(f);assert.equal(f.unlocked,true);assert.equal(f.crops.sunroot,0);assert.equal(f.crops.moonberry,0);f.meal='sunroot';assert.equal(beginExpedition(f,2).hp,135);assert.equal(f.meals.sunroot,0);assert.equal(f.meal,null);assert.equal(beginExpedition(f,2).hp,100);});
check('Watering, fertilizer and persistent soil affect real growth and harvest',()=>{const f=freshFarm();tend(f,4,'sunroot');grow(f,500);assert.equal(f.plots[4].growth,0);tend(f,4,'sunroot');improve(f,4,'soil');improve(f,4,'fertilizer');grow(f,23);assert.equal(f.plots[4].growth,1);tend(f,4,'sunroot',()=>1);assert.equal(f.crops.sunroot,3);assert.equal(f.plots[4].rich,true);assert.equal(f.plots[4].fertilized,false);});
check('Resources cannot be spent twice or go negative',()=>{const f=freshFarm();f.seeds.sunroot=0;const before=JSON.stringify(f);tend(f,4,'sunroot');cook(f,'sunroot');offerHarvest(f);tend(f,-1,'sunroot');assert.equal(JSON.stringify(f),before);assert.throws(()=>beginExpedition(f,2));assert.throws(()=>beginExpedition(f,9));});
check('Dungeon kills yield supplies; rare seeds require deeper dungeon',()=>{const a=emptyLoot(),b=emptyLoot();for(let k=1;k<=33;k++){rewardKill(a,k,1);rewardKill(b,k,2);}assert.equal(a.embercorn,0);assert.equal(b.embercorn,5);assert.equal(a.soil,3);const f=freshFarm();const rewards=settleExpedition(f,b,'won',2);assert.equal(rewards.embercorn,8);assert.equal(f.seeds.embercorn,8);assert.equal(f.runs,1);assert.equal(f.clears,1);});
check('Failure retains half loot and always supplies a recovery seed',()=>{const f=freshFarm();const x=settleExpedition(f,{sunroot:5,moonberry:3,embercorn:0,soil:1,fertilizer:3},'lost',1);assert.equal(x.sunroot,3);assert.equal(x.moonberry,2);assert.equal(x.fertilizer,2);assert.equal(settleExpedition(f,emptyLoot(),'escaped',1).sunroot,1);});
check('Saved gardens round-trip and corrupted saves recover safely',()=>{const f=freshFarm();tend(f,4,'moonberry');assert.deepEqual(hydrateFarm(JSON.parse(JSON.stringify(f))),f);assert.deepEqual(hydrateFarm(null),freshFarm());assert.deepEqual(hydrateFarm({version:1,plots:[]}),freshFarm());f.seeds.sunroot=-90;f.plots[0].growth=Infinity;const h=hydrateFarm(f);assert.equal(h.seeds.sunroot,0);assert.equal(h.plots[0].growth,0);});
console.log(passed+' progression checks passed.');
